const PROFESSIONAL_FORM_SUBMIT = 'PROFESSIONAL_FORM_SUBMIT';
const PERSONAL_FORM_SUBMIT = 'PERSONAL_FORM_SUBMIT';
const INSERT_DOG = 'INSERT_DOG';

export { PROFESSIONAL_FORM_SUBMIT, PERSONAL_FORM_SUBMIT, INSERT_DOG };
